# Application Name
spring.application.name=ApexPay-Banking-Service

# DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/apexpay_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=apexdb
spring.datasource.password=apexpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
# 'update' will create/update tables automatically. For production, use 'validate' or 'none'.
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL being executed in the console (Great for debugging!)
spring.jpa.show-sql=true

# Formats the SQL so it's readable in the console
spring.jpa.properties.hibernate.format_sql=true

# 3. Optional: Shows the values being passed to the SQL parameters
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# The dialect for MySQL 8+
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Hide the stack trace from the API response
server.error.include-stacktrace=never

# Optional: Hide the detailed message if you want it even cleaner
# server.error.include-message=never

# Server Port
server.port=8080

# Swagger UI (SpringDoc) Configuration
# This makes it easy to find your documentation
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.jwt.secret=${JWT_SECRET:YourSuperSecretKeyForLocalDevelopmentAndTestingOnlyMakeItLong}